name: Docker CD

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: Docker Build
      run: docker build -t docker.pkg.github.com/bengreenier/sgx-lkl-turtles/sgx-lkl-turtles:latest .
    - name: Docker Push
      run: docker push docker.pkg.github.com/bengreenier/sgx-lkl-turtles/sgx-lkl-turtles:latest
